//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportAVLData.svCams {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgLastPositionResults", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgLastPositionResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.LastPositionParams[] PositionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.LastPositionParams[] Positions {
            get {
                return this.PositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionsField, value) != true)) {
                    this.PositionsField = value;
                    this.RaisePropertyChanged("Positions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LastPositionParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class LastPositionParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetId AssetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeadingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastHeardGMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastPosHeardGMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetId Assetid {
            get {
                return this.AssetidField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetidField, value) != true)) {
                    this.AssetidField = value;
                    this.RaisePropertyChanged("Assetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Heading {
            get {
                return this.HeadingField;
            }
            set {
                if ((this.HeadingField.Equals(value) != true)) {
                    this.HeadingField = value;
                    this.RaisePropertyChanged("Heading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastHeardGMT {
            get {
                return this.LastHeardGMTField;
            }
            set {
                if ((this.LastHeardGMTField.Equals(value) != true)) {
                    this.LastHeardGMTField = value;
                    this.RaisePropertyChanged("LastHeardGMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastPosHeardGMT {
            get {
                return this.LastPosHeardGMTField;
            }
            set {
                if ((this.LastPosHeardGMTField.Equals(value) != true)) {
                    this.LastPosHeardGMTField = value;
                    this.RaisePropertyChanged("LastPosHeardGMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lng {
            get {
                return this.LngField;
            }
            set {
                if ((this.LngField.Equals(value) != true)) {
                    this.LngField = value;
                    this.RaisePropertyChanged("Lng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetId", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class AssetId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaintenanceRequest", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class MaintenanceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetId AssetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndGMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartGMTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetId Assetid {
            get {
                return this.AssetidField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetidField, value) != true)) {
                    this.AssetidField = value;
                    this.RaisePropertyChanged("Assetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndGMT {
            get {
                return this.EndGMTField;
            }
            set {
                if ((this.EndGMTField.Equals(value) != true)) {
                    this.EndGMTField = value;
                    this.RaisePropertyChanged("EndGMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartGMT {
            get {
                return this.StartGMTField;
            }
            set {
                if ((this.StartGMTField.Equals(value) != true)) {
                    this.StartGMTField = value;
                    this.RaisePropertyChanged("StartGMT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgMaintenanceResults", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgMaintenanceResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.MaintenanceParams[] pkgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.MaintenanceParams[] pkg {
            get {
                return this.pkgField;
            }
            set {
                if ((object.ReferenceEquals(this.pkgField, value) != true)) {
                    this.pkgField = value;
                    this.RaisePropertyChanged("pkg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaintenanceParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class MaintenanceParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetId AssetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndGMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartGMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalMetersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetId Assetid {
            get {
                return this.AssetidField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetidField, value) != true)) {
                    this.AssetidField = value;
                    this.RaisePropertyChanged("Assetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndGMT {
            get {
                return this.EndGMTField;
            }
            set {
                if ((this.EndGMTField.Equals(value) != true)) {
                    this.EndGMTField = value;
                    this.RaisePropertyChanged("EndGMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartGMT {
            get {
                return this.StartGMTField;
            }
            set {
                if ((this.StartGMTField.Equals(value) != true)) {
                    this.StartGMTField = value;
                    this.RaisePropertyChanged("StartGMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalHours {
            get {
                return this.TotalHoursField;
            }
            set {
                if ((this.TotalHoursField.Equals(value) != true)) {
                    this.TotalHoursField = value;
                    this.RaisePropertyChanged("TotalHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalMeters {
            get {
                return this.TotalMetersField;
            }
            set {
                if ((this.TotalMetersField.Equals(value) != true)) {
                    this.TotalMetersField = value;
                    this.RaisePropertyChanged("TotalMeters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgAssetFilterResults", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgAssetFilterResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetFilterParams[] AssetsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetFilterParams[] Assets {
            get {
                return this.AssetsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetsField, value) != true)) {
                    this.AssetsField = value;
                    this.RaisePropertyChanged("Assets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetFilterParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class AssetFilterParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetInfo AInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetFilterParams.ActiveStates ActiveStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetFilterParams.Densities DensityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetInfo AInfo {
            get {
                return this.AInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AInfoField, value) != true)) {
                    this.AInfoField = value;
                    this.RaisePropertyChanged("AInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetFilterParams.ActiveStates ActiveState {
            get {
                return this.ActiveStateField;
            }
            set {
                if ((this.ActiveStateField.Equals(value) != true)) {
                    this.ActiveStateField = value;
                    this.RaisePropertyChanged("ActiveState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetFilterParams.Densities Density {
            get {
                return this.DensityField;
            }
            set {
                if ((this.DensityField.Equals(value) != true)) {
                    this.DensityField = value;
                    this.RaisePropertyChanged("Density");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AssetFilterParams.ActiveStates", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
        public enum ActiveStates : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Deactive = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Active = 1,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AssetFilterParams.Densities", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
        public enum Densities : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Sparse = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Dense = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetInfo", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class AssetInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetId AssetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetName {
            get {
                return this.AssetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetNameField, value) != true)) {
                    this.AssetNameField = value;
                    this.RaisePropertyChanged("AssetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetType {
            get {
                return this.AssetTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetTypeField, value) != true)) {
                    this.AssetTypeField = value;
                    this.RaisePropertyChanged("AssetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetId Assetid {
            get {
                return this.AssetidField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetidField, value) != true)) {
                    this.AssetidField = value;
                    this.RaisePropertyChanged("Assetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgEventFilterResults", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgEventFilterResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, ImportAVLData.svCams.EventFilterParams[]> EventTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, ImportAVLData.svCams.EventFilterParams[]> EventTypes {
            get {
                return this.EventTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTypesField, value) != true)) {
                    this.EventTypesField = value;
                    this.RaisePropertyChanged("EventTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventFilterParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class EventFilterParams : ImportAVLData.svCams.EventFilterBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetType {
            get {
                return this.AssetTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetTypeField, value) != true)) {
                    this.AssetTypeField = value;
                    this.RaisePropertyChanged("AssetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgEventFilterBaseResults", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgEventFilterBaseResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, ImportAVLData.svCams.EventFilterBase[]> EventTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, ImportAVLData.svCams.EventFilterBase[]> EventTypes {
            get {
                return this.EventTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTypesField, value) != true)) {
                    this.EventTypesField = value;
                    this.RaisePropertyChanged("EventTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventFilterBase", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ImportAVLData.svCams.EventFilterParams))]
    public partial class EventFilterBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.EventFilterBase.EventDataTypes EventDataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.EventFilterBase.EventDataTypes EventDataType {
            get {
                return this.EventDataTypeField;
            }
            set {
                if ((this.EventDataTypeField.Equals(value) != true)) {
                    this.EventDataTypeField = value;
                    this.RaisePropertyChanged("EventDataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTypeField, value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="EventFilterBase.EventDataTypes", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
        public enum EventDataTypes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Point = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Line = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgAssetStatesParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgAssetStatesParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<ImportAVLData.svCams.AssetId, ImportAVLData.svCams.AssetStateParams[]> AssetStatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<ImportAVLData.svCams.AssetId, ImportAVLData.svCams.AssetStateParams[]> AssetStates {
            get {
                return this.AssetStatesField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetStatesField, value) != true)) {
                    this.AssetStatesField = value;
                    this.RaisePropertyChanged("AssetStates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetStateParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class AssetStateParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateDscrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateDscr {
            get {
                return this.StateDscrField;
            }
            set {
                if ((object.ReferenceEquals(this.StateDscrField, value) != true)) {
                    this.StateDscrField = value;
                    this.RaisePropertyChanged("StateDscr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgQueryResultParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgQueryResultParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.QueryResultParams[] QueryResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.QueryResultParams[] QueryResults {
            get {
                return this.QueryResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryResultsField, value) != true)) {
                    this.QueryResultsField = value;
                    this.RaisePropertyChanged("QueryResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class QueryResultParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetInfo AInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.QueryResultParams.Densities DensityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeGMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeGMTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetInfo AInfo {
            get {
                return this.AInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AInfoField, value) != true)) {
                    this.AInfoField = value;
                    this.RaisePropertyChanged("AInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.QueryResultParams.Densities Density {
            get {
                return this.DensityField;
            }
            set {
                if ((this.DensityField.Equals(value) != true)) {
                    this.DensityField = value;
                    this.RaisePropertyChanged("Density");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTimeGMT {
            get {
                return this.EndTimeGMTField;
            }
            set {
                if ((this.EndTimeGMTField.Equals(value) != true)) {
                    this.EndTimeGMTField = value;
                    this.RaisePropertyChanged("EndTimeGMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTypeField, value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTimeGMT {
            get {
                return this.StartTimeGMTField;
            }
            set {
                if ((this.StartTimeGMTField.Equals(value) != true)) {
                    this.StartTimeGMTField = value;
                    this.RaisePropertyChanged("StartTimeGMT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultParams.Densities", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
        public enum Densities : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Sparse = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Dense = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgRealtimePointResults", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgRealtimePointResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<ImportAVLData.svCams.AssetId, ImportAVLData.svCams.RealtimePointParams[]> RTPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<ImportAVLData.svCams.AssetId, ImportAVLData.svCams.RealtimePointParams[]> RTPoints {
            get {
                return this.RTPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.RTPointsField, value) != true)) {
                    this.RTPointsField = value;
                    this.RaisePropertyChanged("RTPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealtimePointParams", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class RealtimePointParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeGMTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lng {
            get {
                return this.LngField;
            }
            set {
                if ((this.LngField.Equals(value) != true)) {
                    this.LngField = value;
                    this.RaisePropertyChanged("Lng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeGMT {
            get {
                return this.TimeGMTField;
            }
            set {
                if ((this.TimeGMTField.Equals(value) != true)) {
                    this.TimeGMTField = value;
                    this.RaisePropertyChanged("TimeGMT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlotPointRequest", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PlotPointRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.EventAssetId EAIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndGMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartGMTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.EventAssetId EAId {
            get {
                return this.EAIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EAIdField, value) != true)) {
                    this.EAIdField = value;
                    this.RaisePropertyChanged("EAId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndGMT {
            get {
                return this.EndGMTField;
            }
            set {
                if ((this.EndGMTField.Equals(value) != true)) {
                    this.EndGMTField = value;
                    this.RaisePropertyChanged("EndGMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartGMT {
            get {
                return this.StartGMTField;
            }
            set {
                if ((this.StartGMTField.Equals(value) != true)) {
                    this.StartGMTField = value;
                    this.RaisePropertyChanged("StartGMT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventAssetId", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class EventAssetId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImportAVLData.svCams.AssetId AssetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportAVLData.svCams.AssetId Assetid {
            get {
                return this.AssetidField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetidField, value) != true)) {
                    this.AssetidField = value;
                    this.RaisePropertyChanged("Assetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PkgPlotPointResults", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PkgPlotPointResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<ImportAVLData.svCams.EventId, ImportAVLData.svCams.RealtimePointParams[]> PlotPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<ImportAVLData.svCams.EventId, ImportAVLData.svCams.RealtimePointParams[]> PlotPoints {
            get {
                return this.PlotPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlotPointsField, value) != true)) {
                    this.PlotPointsField = value;
                    this.RaisePropertyChanged("PlotPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventId", Namespace="http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class EventId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svCams.ICAMSDataInterface")]
    public interface ICAMSDataInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAll", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAllResponse")]
        ImportAVLData.svCams.PkgLastPositionResults GetLastPositionInfoAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAll", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAllResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgLastPositionResults> GetLastPositionInfoAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfo", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoResponse")]
        ImportAVLData.svCams.PkgLastPositionResults GetLastPositionInfo(ImportAVLData.svCams.AssetId[] ads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfo", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgLastPositionResults> GetLastPositionInfoAsync(ImportAVLData.svCams.AssetId[] ads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfo", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfoResponse")]
        ImportAVLData.svCams.PkgMaintenanceResults GetMaintenanceInfo(ImportAVLData.svCams.MaintenanceRequest[] mr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfo", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfoResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgMaintenanceResults> GetMaintenanceInfoAsync(ImportAVLData.svCams.MaintenanceRequest[] mr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssets", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssetsResponse")]
        ImportAVLData.svCams.PkgAssetFilterResults GetMaintenanceAssets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssets", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssetsResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgAssetFilterResults> GetMaintenanceAssetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetAssetFilters", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetAssetFiltersResponse")]
        ImportAVLData.svCams.PkgAssetFilterResults GetAssetFilters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetAssetFilters", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetAssetFiltersResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgAssetFilterResults> GetAssetFiltersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetEventFilters", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetEventFiltersResponse")]
        ImportAVLData.svCams.PkgEventFilterResults GetEventFilters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetEventFilters", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetEventFiltersResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgEventFilterResults> GetEventFiltersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAsset", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAssetResponse")]
        ImportAVLData.svCams.PkgEventFilterBaseResults GetEventFiltersFromAsset(ImportAVLData.svCams.AssetId aid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAsset", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAssetResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgEventFilterBaseResults> GetEventFiltersFromAssetAsync(ImportAVLData.svCams.AssetId aid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetAssetStates", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetAssetStatesResponse")]
        ImportAVLData.svCams.PkgAssetStatesParams GetAssetStates(ImportAVLData.svCams.AssetId[] ads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetAssetStates", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetAssetStatesResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgAssetStatesParams> GetAssetStatesAsync(ImportAVLData.svCams.AssetId[] ads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetEvents", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetEventsResponse")]
        ImportAVLData.svCams.PkgQueryResultParams GetEvents(ImportAVLData.svCams.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetEvents", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetEventsResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgQueryResultParams> GetEventsAsync(ImportAVLData.svCams.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetRealtimePoints", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetRealtimePointsResponse")]
        ImportAVLData.svCams.PkgRealtimePointResults GetRealtimePoints(ImportAVLData.svCams.AssetId aid, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetRealtimePoints", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetRealtimePointsResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgRealtimePointResults> GetRealtimePointsAsync(ImportAVLData.svCams.AssetId aid, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetPlotData", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetPlotDataResponse")]
        ImportAVLData.svCams.PkgPlotPointResults GetPlotData(ImportAVLData.svCams.PlotPointRequest[] req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAMSDataInterface/GetPlotData", ReplyAction="http://tempuri.org/ICAMSDataInterface/GetPlotDataResponse")]
        System.Threading.Tasks.Task<ImportAVLData.svCams.PkgPlotPointResults> GetPlotDataAsync(ImportAVLData.svCams.PlotPointRequest[] req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICAMSDataInterfaceChannel : ImportAVLData.svCams.ICAMSDataInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAMSDataInterfaceClient : System.ServiceModel.ClientBase<ImportAVLData.svCams.ICAMSDataInterface>, ImportAVLData.svCams.ICAMSDataInterface {
        
        public CAMSDataInterfaceClient() {
        }
        
        public CAMSDataInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CAMSDataInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAMSDataInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAMSDataInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ImportAVLData.svCams.PkgLastPositionResults GetLastPositionInfoAll() {
            return base.Channel.GetLastPositionInfoAll();
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgLastPositionResults> GetLastPositionInfoAllAsync() {
            return base.Channel.GetLastPositionInfoAllAsync();
        }
        
        public ImportAVLData.svCams.PkgLastPositionResults GetLastPositionInfo(ImportAVLData.svCams.AssetId[] ads) {
            return base.Channel.GetLastPositionInfo(ads);
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgLastPositionResults> GetLastPositionInfoAsync(ImportAVLData.svCams.AssetId[] ads) {
            return base.Channel.GetLastPositionInfoAsync(ads);
        }
        
        public ImportAVLData.svCams.PkgMaintenanceResults GetMaintenanceInfo(ImportAVLData.svCams.MaintenanceRequest[] mr) {
            return base.Channel.GetMaintenanceInfo(mr);
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgMaintenanceResults> GetMaintenanceInfoAsync(ImportAVLData.svCams.MaintenanceRequest[] mr) {
            return base.Channel.GetMaintenanceInfoAsync(mr);
        }
        
        public ImportAVLData.svCams.PkgAssetFilterResults GetMaintenanceAssets() {
            return base.Channel.GetMaintenanceAssets();
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgAssetFilterResults> GetMaintenanceAssetsAsync() {
            return base.Channel.GetMaintenanceAssetsAsync();
        }
        
        public ImportAVLData.svCams.PkgAssetFilterResults GetAssetFilters() {
            return base.Channel.GetAssetFilters();
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgAssetFilterResults> GetAssetFiltersAsync() {
            return base.Channel.GetAssetFiltersAsync();
        }
        
        public ImportAVLData.svCams.PkgEventFilterResults GetEventFilters() {
            return base.Channel.GetEventFilters();
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgEventFilterResults> GetEventFiltersAsync() {
            return base.Channel.GetEventFiltersAsync();
        }
        
        public ImportAVLData.svCams.PkgEventFilterBaseResults GetEventFiltersFromAsset(ImportAVLData.svCams.AssetId aid) {
            return base.Channel.GetEventFiltersFromAsset(aid);
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgEventFilterBaseResults> GetEventFiltersFromAssetAsync(ImportAVLData.svCams.AssetId aid) {
            return base.Channel.GetEventFiltersFromAssetAsync(aid);
        }
        
        public ImportAVLData.svCams.PkgAssetStatesParams GetAssetStates(ImportAVLData.svCams.AssetId[] ads) {
            return base.Channel.GetAssetStates(ads);
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgAssetStatesParams> GetAssetStatesAsync(ImportAVLData.svCams.AssetId[] ads) {
            return base.Channel.GetAssetStatesAsync(ads);
        }
        
        public ImportAVLData.svCams.PkgQueryResultParams GetEvents(ImportAVLData.svCams.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT) {
            return base.Channel.GetEvents(ads, atypes, etypes, startTimeGMT, endTimeGMT);
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgQueryResultParams> GetEventsAsync(ImportAVLData.svCams.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT) {
            return base.Channel.GetEventsAsync(ads, atypes, etypes, startTimeGMT, endTimeGMT);
        }
        
        public ImportAVLData.svCams.PkgRealtimePointResults GetRealtimePoints(ImportAVLData.svCams.AssetId aid, System.DateTime start, System.DateTime end) {
            return base.Channel.GetRealtimePoints(aid, start, end);
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgRealtimePointResults> GetRealtimePointsAsync(ImportAVLData.svCams.AssetId aid, System.DateTime start, System.DateTime end) {
            return base.Channel.GetRealtimePointsAsync(aid, start, end);
        }
        
        public ImportAVLData.svCams.PkgPlotPointResults GetPlotData(ImportAVLData.svCams.PlotPointRequest[] req) {
            return base.Channel.GetPlotData(req);
        }
        
        public System.Threading.Tasks.Task<ImportAVLData.svCams.PkgPlotPointResults> GetPlotDataAsync(ImportAVLData.svCams.PlotPointRequest[] req) {
            return base.Channel.GetPlotDataAsync(req);
        }
    }
}
