//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportAVLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgPickupB
    {
        public int ID { get; set; }
        public string SysWithDate { get; set; }
        public Nullable<int> SysID { get; set; }
        public Nullable<System.DateTime> ActivityTime { get; set; }
        public string StateDesc { get; set; }
        public System.Data.Entity.Spatial.DbGeometry ShapeAgg { get; set; }
        public System.Data.Entity.Spatial.DbGeometry ShapeLineAgg { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public Nullable<int> SumOfSec { get; set; }
        public Nullable<double> SumOfDistance { get; set; }
        public string VehicleType { get; set; }
    }
}
