//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportAVLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraderStateLookUp
    {
        public int ID { get; set; }
        public Nullable<int> SpeedMin { get; set; }
        public Nullable<int> SpeedMax { get; set; }
        public string Dsr { get; set; }
    }
}
