//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportAVLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateList
    {
        public int ID { get; set; }
        public Nullable<int> SysId { get; set; }
        public string VehicleType { get; set; }
        public Nullable<int> State { get; set; }
        public string StateDesc { get; set; }
    }
}
